### ISSUE TITLE
How to retrieve the value in a few level down the nodes?

### ISSUE THREAD

**Issue by alitavector** [nfarina/xmldoc#13]
Updated code:
How does the childrenNamed is use with eachChild for looping? It's simply return undefined error and need to get one of more ```step``` value in each measure?
```
fs.readFile('Test1.xml', 'utf-8', function(err, data) {
	if (err) throw err;
	var document = new xmldoc.XmlDocument(data);
	
	//Get all <measure>...</measure> contents in part element
	var dd=document.childNamed("part").childrenNamed("measure")
	
	//Loop each measure element
	dd.eachChild(function (measure) {   //Error
		//If <pitch> exist, get it
	});
});

XML file:
<measure id="1">
<note>
  <pitch>
    <step>A</step>
  </pitch>
</note>
<note>
  <pitch>
    <step>B</step>
  </pitch>
</note>
<note>
  <pitch>
    <step>C</step>
  </pitch>
</note>
</measure>
<measure id="2">
...
</measure>
```

Uncaught node.js Error 
TypeError: undefined is not a function
    at file:///D:/testfolder/index.html:44:5
    at fs.js:289:14
    at Object.oncomplete (fs.js:97:15)

**Comment by nfarina** [comment]
Hello, `childrenNamed()` simply returns a native JS array, so you can't call `eachChild()` on it. You can loop through it the old-fashioned way with something like `for (var i=0; i<dd.length; i++)` etc. Hope this helps!
