### ISSUE TITLE
Question on usage

### ISSUE THREAD

**Issue by wpmjones** [nfarina/xmldoc#20]
Below are the two types of responses that my lighting system can return.  The first is a yes/no on whether a request was successful.  A status of 200 = success, 404 = failure.

```xml
<?xml version="1.0" encoding="UTF-8"?><RestResponse succeeded="true"><status>200</status></RestResponse>
```

This is a response from a status request on any one light.  Value (0-255) and formatted (0%-100%) are both a brightness status of the light.

```xml
<?xml version="1.0" encoding="UTF-8"?><properties><property id="ST" value="140" formatted="55" uom="%/on/off"/></properties>
```

I'm trying to parse this XML to provide user feedback.  For the status, all I really need is  a success/fail response (Your request was successful).  For the second example, I want to be able to pull the formatted value and provide it to the user (The light is on with 55% brightness).

Following is my coffeescript attempt at using xmldoc (commented section was my previous attempt which worked well for status but not for formatted).  When I run it, result comes back blank.  Any thoughts?

```coffeescript
parseBody = (response, callback) ->
  status = new XmlDocument(response)
  result = status.firstChild.attr.status
#  if response.indexOf("status") >= 0
#    start = response.indexOf("status") + 7
#  else
#    result = response.indexOf("formatted") + 10
#  stop = start + 3
#  result = response.slice(start, stop)
  return callback (result)
```

**Comment by nfarina** [comment]
I think you want:

```coffee
result = status.firstChild.firstChild.val
```

or, to be more explicit:

```coffee
result = status.valueWithPath "RestResponse.status"
```

**Comment by nfarina** [comment]
And for the second example:

```coffee
brightness = status.firstChild.firstChild.attr["formatted"]
```

Or the fancier version:

```coffee
brightness = status.valueWithPath "properties.property@formatted"
```

**Comment by wpmjones** [comment]
I gave it a shot, but no luck.  Here is a test script that I set up just to see if it would work.

```coffeescript
xmldoc = require('xmldoc')

module.exports = (robot) ->
  robot.respond /goweb/i, (res) ->
    status = new XmlDocument('<?xml version="1.0" encoding="UTF-8"?><RestResponse succeeded="true"><status>200</status></RestResponse>')
    result = status.valueWithPath "RestResponse.status"
#    result = status.valueWithPath "properties.property@formatted"
    res.send "result: #{result}"
```

**Comment by nfarina** [comment]
That sounds like an import problem not specific to xmldoc. You are `require`ing the `xmldoc` module itself but not `XmlDocument` itself. Try this:

```coffee
status = new xmldoc.XmlDocument(...)
```

Or you can use CoffeeScript's "destructuring assignment" in the require line at the top:

```coffee
{ XmlDocument, XmlElement } = require('xmldoc')
```
