### ISSUE TITLE
Error parsing coments out of XML scope

### ISSUE THREAD

**Issue by ascher** [nfarina/xmldoc#27]
Create any valid XML, then after the last line, insert a comment :  
it'll crash with : 
services/node_modules/xmldoc/lib/xmldoc.js:224
function parser_text() { delegates[0]._text.apply(delegates[0],arguments) }
                                     ^

TypeError: Cannot read property '_text' of undefined

Comments inside the XML doc won't generate this error.

**Comment by dsincl12** [comment]
Put this tag at the end of an XML document and you will get the same error as well (from Arbortext, Inc., 1988-2008, v.4002).

<?Pub *0000003434 0?>

**Comment by nfarina** [comment]
Thanks! I can reproduce this - working on a fix now.
