### ISSUE TITLE
While writing back xml document to a file it removes all comments

### ISSUE THREAD

**Issue by Ajay-MS** [nfarina/xmldoc#39]
Hello Team,

I have an sample.xml file which contains comments also. Using xmldoc when i first convert it into a DOM structure and again write back dom to file it writes without comment.  I think all comments are being committed  by xmldoc when creating a DOM structure itself.

**Comment by nfarina** [comment]
Hi Ajay - The design goal of `xmldoc` was to be a "reader" of XML, and not a complete "XML Document Editor". Although it can "print out" XML documents, it makes no guarantees of round-trip accuracy, as you've experienced with comment nodes.

I do recognize that a lot of people wish for this functionality though, so if you would like to submit a PR that adds this functionality, in a way that doesn't add much complexity or new lines of code to the module, then I would be happy to review it!

**Comment by nfarina** [comment]
Closed by #43 - let me know if this doesn't work for you!
