### ISSUE TITLE
Order of elements changed

### ISSUE THREAD

**Issue by benlowry** [nfarina/xmldoc#41]
I have a pretty standard signin form I'm parsing and when converting back to a string the order changes:

```
<label for='checkbox'>
    <input id='checkbox' name='checkbox' />
    Remember I'm signed in
</label>
```

Becomes:

```
<label for='checkbox'>
    Remember I'm signed in
    <input id='checkbox' name='checkbox' />
</label>
```

**Comment by nfarina** [comment]
This is expected I'm afraid - the document structure discards the order information of text nodes as they relate to element nodes. Remember that `xmldoc` is only intended to be a read-only library and `toString()` is for debugging only! XML "round trip" correctness is not guaranteed.
