### ISSUE TITLE
Word of thanks.

### ISSUE THREAD

**Issue by stanislaw** [nfarina/xmldoc#45]
Hi @nfarina,

This is just a word of thanks from an engineer working at Uberchord GmbH. We have to deal with MusicXML extensively and recently we got to rewriting our Objective-C MusicXML parser on JS.

We started with `xml2js` but eventually found that it didn't give us what we needed:

ability to access children of a node in the same order as they appear in an MusicXML document. I found that `xmldoc` allows that and have already rewritten our `musicxml.js` parser to be based on `xmldoc`. 

Just for the information `xml2js` produces a Javascript Object with a certain structure which you cannot query for things like `.children` as the children are already grouped by tags while we need to be able to have them raw un-grouped like:

```
<measure>
  <note>...</note>
  <forward></forward
  <note>...</note>
</measure>
```

We want to be able to query `measureXML.children` to get enumeration over both `note` and `forward` tags while `xml2js` groups `note` to one array and `forward` to another so we cannot enumerate though them mixed.

Just wanted to let you know which feature was crucial for us and say a big thanks for you as a developer of `xmldoc`.

Thanks. Opening and closing this issue immediately :)

**Comment by nfarina** [comment]
Hey thanks so much for writing this up, I am so glad you are finding the library useful!
