### ISSUE TITLE
How to change the value of a node?

### ISSUE THREAD

**Issue by twilco** [nfarina/xmldoc#47]
Can I get a node and then change it's value?  For example:

    var document = new xmldoc.XmlDocument(xmlString);     
    document.descendantWithPath('xfa:data.EFormsData.InsuredData.Name.FirstName').val = "Test";

**Comment by nfarina** [comment]
Working on a fix for this in the `convert-val-to-property` branch.

**Comment by nfarina** [comment]
This never got finished, and this issue is quite old, so I'm closing it for now unless someone else would like to tackle it in a PR.

**Comment by khalilou88** [comment]
Hi, I need the same feature, any workaround ?
