### ISSUE TITLE
In some cases, missing closing tags are not a parse error

### ISSUE THREAD

**Issue by xlash123** [nfarina/xmldoc#54]
While it is nice that some closing tags don't need to be there and parser still understands the XML document, XML standard says that a close tag can not be omitted in any circumstance. I'm making an application that will verify that an XML document meets certain standards, and some XML parsers will not parse if the closing tag is missing. Perhaps you could make a toggle for either method, unless there's already a way to detect missing closing tags.

Edit: By "in some cases," I mean cases when the closing tag is at the end of the document.

**Comment by nfarina** [comment]
Hello, so the actual XML parsing is done by [sax](https://github.com/isaacs/sax-js) in "strict" mode under the hood. You might check that `sax` itself raises an error with your document - if not, I wouldn't be surprised, as it's not a 100% standards-compliant sort of library, more like a "get it done" library. If `sax` _does_ raise an error and we aren't handling that somehow, then that's something we could fix.

**Comment by xlash123** [comment]
After looking through the `sax` source code, there is no check to confirm that an tag has both open and close. It'll only process a closing tag when it comes to it.
