### ISSUE TITLE
flattening seems to be working erroneously

### ISSUE THREAD

**Issue by RachelSatoyama** [nfarina/xmldoc#55]
following code:
```javascript
new xmldoc.XmlDocument('<div>some <span/> some</div>').toString({
    compressed: true
  });
```
returns `<div>some<span/>some</div>` while I'm expecting to see `<div>some <span/> some</div>`

**Comment by nfarina** [comment]
I think you're looking for the `preserveWhitespace` option:

```js
new XmlDocument('<div>some <span/> some</div>').toString({
    compressed: true,
    preserveWhitespace: true
});
```

returns `<div>some <span/> some</div>`

**Comment by adabru** [comment]
Is there a reason the option is not set by default?

**Comment by nfarina** [comment]
Only because `toString()` was originally just for debugging.
