### ISSUE TITLE
Exporting Node types.

### ISSUE THREAD

**Issue by aleph1** [nfarina/xmldoc#64]
I am using xmldoc to modify existing xml structures and it works well, however I have to modify the code to allow exports of the additional node types (XmlElement, XmlTextNode, XmlCDataNode, XmlCommentNode). Is there a reason why the module export isn't like the following?

if (typeof module !== 'undefined' && module.exports && !global.xmldocAssumeBrowser)
    module.exports.XmlDocument = XmlDocument;
    module.exports.XmlElement = XmlElement;
    module.exports.XmlTextNode = XmlTextNode;
    module.exports.XmlCDataNode = XmlCDataNode;
    module.exports.XmlCommentNode = XmlCommentNode;
else
    this.XmlDocument = XmlDocument;
    this.XmlElement = XmlElement;
    this.XmlTextNode = XmlTextNode;
    this.XmlCDataNode = XmlCDataNode;
    this.XmlCommentNode = XmlCommentNode;
}

**Comment by nfarina** [comment]
No reason! Happy to merge a PR if you don't mind making one.
