### ISSUE TITLE
Add text as child nodes

### ISSUE THREAD

**Issue by tolu** [nfarina/xmldoc#7]
Im currently working on a converter from ttml-files to webvtt (closed captioning formats) where I need to know the order of children to convert correctly.
If plain text were added as nodes (as an option?) this would be much easier.

A caption in the ttml-file can look like this:
```xml
<p begin="..." dur="..." style="left">
        <span style="italic"> -Betjent Jason Stackhouse. </span>
        <br />-Hvor er du? Du må hjelpe meg.
</p>
```
Parsing a node like this leaves me helpless as to know which text comes first since the object looks something like this:

```json
{
"val" : "-Hvor er du? Du må hjelpe meg.",
"children" : [ { "name": "span", ...}, { "name": "br", ...} ]
}
```

To make it work for me, this is what I do right now
```js
XmlElement.prototype._text = function(text) {
  if (text) { 
    this.val += text;
    
    // create nodes for text value also
    text = text.trim();
    if(text.length){
      var child = new XmlElement({ name: 'text' });
      child.val = text;

      // add to our children array
      this.children.push(child);

      // update first/last pointers
      if (!this.firstChild) this.firstChild = child;
      this.lastChild = child;

      delegates.unshift(child);
      delegates.shift();
    }
  }
}
```

**Comment by nfarina** [comment]
Really late follow-up on this, sorry! I think an option for this would be great. If you have the time to create a PR from your solution I would love to add this.

**Comment by tolu** [comment]
No problem! And of course! Thanks for the follow up, know the feeling :)

**Comment by nfarina** [comment]
Closing this; see #16 for explanation.
