### ISSUE TITLE
getValueWithPath - xml namespace not supported?

### ISSUE THREAD

**Issue by lafar6502** [nfarina/xmldoc#9]
Hi, does the library support xml namespaces at all? I'm trying to parse a SOAP document and the getValueWithPath function doesn't seem to work.

**Comment by kf6kjg** [comment]
File named test.xml containing the following:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<office:document-content xmlns:office="urn:oasis:names:tc:opendocument:xmlns:office:1.0" xmlns:draw="urn:oasis:names:tc:opendocument:xmlns:drawing:1.0" xmlns:presentation="urn:oasis:names:tc:opendocument:xmlns:presentation:1.0" office:version="1.2">
	<office:body>
		<office:presentation>
			<presentation:date-time-decl presentation:name="dtd1" presentation:source="current-date" style:data-style-name="D1"/>
			<draw:page draw:name="Some Text" draw:style-name="dp1" draw:master-page-name="Default" presentation:use-date-time-name="dtd1">
				Just a hacked-in text node...
			</draw:page>
		</office:presentation>
	</office:body>
</office:document-content>
```
You'll note that is is a hand-trimmed section of an Open Document Presentation, as output by LibrOffice and extracted from the resulting zipped ODP file.  It's what I'm trying to process as a CLI tool! :)
Test code:
```javascript
var fs = require('fs');
var xmldoc = require('xmldoc');

fs.readFile(source_xml_file, function(err, data) {
	var xmlroot = new xmldoc.XmlDocument(data);

	console.log("----------\n", xmlroot.firstChild.name, "\n", xmlroot.firstChild.toString()); // works
	console.log("----------\n", xmlroot.childNamed("office:body")); // works.
	console.log("----------\n", xmlroot.childNamed("body")); // Fails as expected, and is as it should be.
	console.log("----------\n", xmlroot.childrenNamed("office:body")); // Works
	console.log("----------\n", xmlroot.valueWithPath("office:document-content.office:body.office:presentation.draw:page")); // null
	console.log("----------\n", xmlroot.descendantWithPath("office:document-content.office:body.office:presentation.draw:page")); // undefined
});
```

It's likely your custom path parser doesn't like the colons.  However, as I personally need to iterate over all <draw:page> elements in the tree and in each extract all text nodes that are children at any level of all <text:p> elements under each page, I think I need to go to xpath+xmldom - not a problem for me as I'm only building a CLI tool, not a responsive web system!

Hope this helps explain the issue and is accurate to what the OP was having problems with.

**Comment by nfarina** [comment]
Thanks for the detailed example!

So `xmldoc` uses the [sax-js](https://github.com/isaacs/sax-js) parser under the hood. It seems like Sax is basically ignoring the "namespace colons" and treating the strings as simple XML tag names. Which should be fine.

I think your example isn't working because you are including the tag name of the root node as part of your path. This works for me:

    console.log("----------\n", xmlroot.valueWithPath("office:body.office:presentation.draw:page"));
    console.log("----------\n", xmlroot.descendantWithPath("office:body.office:presentation.draw:page"));
